// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.XrmDbExport.V1.Tenants.Item.EntitiesToExcel1;
using Qwips.Core.Pointer.XrmDbExport.V1.Tenants.Item.ExportToExcel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.XrmDbExport.V1.Tenants.Item {
    /// <summary>
    /// Builds and executes requests for operations under \xrm-db-export\v1\tenants\{tenantId}
    /// </summary>
    public class WithTenantItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The entitiesToExcel1 property</summary>
        public EntitiesToExcel1RequestBuilder EntitiesToExcel1 { get =>
            new EntitiesToExcel1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exportToExcel property</summary>
        public ExportToExcelRequestBuilder ExportToExcel { get =>
            new ExportToExcelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WithTenantItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-db-export/v1/tenants/{tenantId}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithTenantItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-db-export/v1/tenants/{tenantId}", rawUrl) {
        }
    }
}
