// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.XrmEmail.V1.Tenants.Item.EmailProviders.Item.SendEmail;
using Qwips.Core.Pointer.XrmEmail.V1.Tenants.Item.EmailProviders.Item.Setup;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.XrmEmail.V1.Tenants.Item.EmailProviders.Item {
    /// <summary>
    /// Builds and executes requests for operations under \xrm-email\v1\tenants\{tenantId}\emailProviders\{integrationId}
    /// </summary>
    public class WithIntegrationItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The sendEmail property</summary>
        public SendEmailRequestBuilder SendEmail { get =>
            new SendEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setup property</summary>
        public SetupRequestBuilder Setup { get =>
            new SetupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WithIntegrationItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIntegrationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-email/v1/tenants/{tenantId}/emailProviders/{integrationId}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithIntegrationItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIntegrationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-email/v1/tenants/{tenantId}/emailProviders/{integrationId}", rawUrl) {
        }
    }
}
