// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.SkmXrm.V1beta1.Tenants.Item.Azure.CronDaily;
using Qwips.Core.Pointer.SkmXrm.V1beta1.Tenants.Item.Azure.InitIntegration;
using Qwips.Core.Pointer.SkmXrm.V1beta1.Tenants.Item.Azure.SyncDriveDelta;
using Qwips.Core.Pointer.SkmXrm.V1beta1.Tenants.Item.Azure.TodoPatchIntegration;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.SkmXrm.V1beta1.Tenants.Item.Azure {
    /// <summary>
    /// Builds and executes requests for operations under \skm-xrm\v1beta1\tenants\{tenantId}\azure
    /// </summary>
    public class AzureRequestBuilder : BaseRequestBuilder {
        /// <summary>The cronDaily property</summary>
        public CronDailyRequestBuilder CronDaily { get =>
            new CronDailyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The initIntegration property</summary>
        public InitIntegrationRequestBuilder InitIntegration { get =>
            new InitIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The syncDriveDelta property</summary>
        public SyncDriveDeltaRequestBuilder SyncDriveDelta { get =>
            new SyncDriveDeltaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The todoPatchIntegration property</summary>
        public TodoPatchIntegrationRequestBuilder TodoPatchIntegration { get =>
            new TodoPatchIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new AzureRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AzureRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/skm-xrm/v1beta1/tenants/{tenantId}/azure", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new AzureRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AzureRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/skm-xrm/v1beta1/tenants/{tenantId}/azure", rawUrl) {
        }
    }
}
