// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.SkmXrm.V1beta1.EventHandlers.WebhookRxOnePubSubV1;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.SkmXrm.V1beta1.EventHandlers {
    /// <summary>
    /// Builds and executes requests for operations under \skm-xrm\v1beta1\eventHandlers
    /// </summary>
    public class EventHandlersRequestBuilder : BaseRequestBuilder {
        /// <summary>The webhookRxOnePubSubV1 property</summary>
        public WebhookRxOnePubSubV1RequestBuilder WebhookRxOnePubSubV1 { get =>
            new WebhookRxOnePubSubV1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new EventHandlersRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventHandlersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/skm-xrm/v1beta1/eventHandlers", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new EventHandlersRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventHandlersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/skm-xrm/v1beta1/eventHandlers", rawUrl) {
        }
    }
}
