// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.XrmAzureAdmin.V1.Tenants.Item.Sync.AzureUsers;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.XrmAzureAdmin.V1.Tenants.Item.Sync {
    /// <summary>
    /// Builds and executes requests for operations under \xrm-azure-admin\v1\tenants\{tenantId}\sync
    /// </summary>
    public class SyncRequestBuilder : BaseRequestBuilder {
        /// <summary>The azureUsers property</summary>
        public AzureUsersRequestBuilder AzureUsers { get =>
            new AzureUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new SyncRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-azure-admin/v1/tenants/{tenantId}/sync", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new SyncRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-azure-admin/v1/tenants/{tenantId}/sync", rawUrl) {
        }
    }
}
