// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.Subtenants;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.TenantConfig;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.TenantIntegrations;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.TenantUserRoles;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.TenantUsers;
using Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item.TodoInitTenant;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.Core.Pointer.XrmTenants.V1beta1.Tenants.Item {
    /// <summary>
    /// Builds and executes requests for operations under \xrm-tenants\v1beta1\tenants\{tenantId}
    /// </summary>
    public class WithTenantItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The subtenants property</summary>
        public SubtenantsRequestBuilder Subtenants { get =>
            new SubtenantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenantConfig property</summary>
        public TenantConfigRequestBuilder TenantConfig { get =>
            new TenantConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenantIntegrations property</summary>
        public TenantIntegrationsRequestBuilder TenantIntegrations { get =>
            new TenantIntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenantUserRoles property</summary>
        public TenantUserRolesRequestBuilder TenantUserRoles { get =>
            new TenantUserRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenantUsers property</summary>
        public TenantUsersRequestBuilder TenantUsers { get =>
            new TenantUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The todoInitTenant property</summary>
        public TodoInitTenantRequestBuilder TodoInitTenant { get =>
            new TodoInitTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WithTenantItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-tenants/v1beta1/tenants/{tenantId}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithTenantItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/xrm-tenants/v1beta1/tenants/{tenantId}", rawUrl) {
        }
    }
}
