// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets Decision</summary>
    public enum Body134_plus_DecisionEnum {
        [EnumMember(Value = "QUOTE_ACCEPTED")]
        QUOTE_ACCEPTED,
        [EnumMember(Value = "QUOTE_DECLINE")]
        QUOTE_DECLINE,
    }
}
