// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets UserEntityType</summary>
    public enum Body69_plus_UserEntityTypeEnum {
        [EnumMember(Value = "tenantUsers")]
        TenantUsers,
        [EnumMember(Value = "employees")]
        Employees,
        [EnumMember(Value = "customers")]
        Customers,
        [EnumMember(Value = "contactPersons")]
        ContactPersons,
        [EnumMember(Value = "suppliers")]
        Suppliers,
    }
}
