// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets VismaNetInvoiceStatus</summary>
    public enum Body56_plus_VismaNetInvoiceStatusEnum {
        [EnumMember(Value = "HOLD")]
        HOLD,
        [EnumMember(Value = "BALANCED")]
        BALANCED,
        [EnumMember(Value = "VOIDED")]
        VOIDED,
        [EnumMember(Value = "SCHEDULED")]
        SCHEDULED,
        [EnumMember(Value = "OPEN")]
        OPEN,
        [EnumMember(Value = "CLOSED")]
        CLOSED,
        [EnumMember(Value = "PENDING_PRINT")]
        PENDING_PRINT,
        [EnumMember(Value = "PENDING_EMAIL")]
        PENDING_EMAIL,
        [EnumMember(Value = "CREDIT_HOLD")]
        CREDIT_HOLD,
        [EnumMember(Value = "CC_HOLD")]
        CC_HOLD,
        [EnumMember(Value = "RESERVED")]
        RESERVED,
    }
}
