// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets AppliesToEntityType</summary>
    public enum Body42_plus_AppliesToEntityTypeEnum {
        [EnumMember(Value = "tasks")]
        Tasks,
    }
}
