// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets TypeCategory1</summary>
    public enum Body27_plus_TypeCategory1Enum {
        [EnumMember(Value = "Diverse")]
        Diverse,
        [EnumMember(Value = "Utvikling")]
        Utvikling,
        [EnumMember(Value = "Design")]
        Design,
    }
}
