// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets StatusPhase</summary>
    public enum Body41_plus_StatusPhaseEnum {
        [EnumMember(Value = "BACKLOG")]
        BACKLOG,
        [EnumMember(Value = "OPEN")]
        OPEN,
        [EnumMember(Value = "CLOSED")]
        CLOSED,
    }
}
