// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets TemplateCategory</summary>
    public enum Body37_plus_TemplateCategoryEnum {
        [EnumMember(Value = "OTHER")]
        OTHER,
        [EnumMember(Value = "SO_ORDER_CONFIRMATION")]
        SO_ORDER_CONFIRMATION,
        [EnumMember(Value = "SO_PACKING_SLIP")]
        SO_PACKING_SLIP,
        [EnumMember(Value = "SQ_QUOTE")]
        SQ_QUOTE,
        [EnumMember(Value = "SQ_PRICE_ESTIMATE")]
        SQ_PRICE_ESTIMATE,
        [EnumMember(Value = "WO_ORDER")]
        WO_ORDER,
        [EnumMember(Value = "WO_CONSIGNMENT_NOTE")]
        WO_CONSIGNMENT_NOTE,
        [EnumMember(Value = "WO_CERTIFICATE")]
        WO_CERTIFICATE,
        [EnumMember(Value = "NEWSLETTER")]
        NEWSLETTER,
        [EnumMember(Value = "CS_CONTRACT")]
        CS_CONTRACT,
        [EnumMember(Value = "SO_INVOICE_PREVIEW")]
        SO_INVOICE_PREVIEW,
        [EnumMember(Value = "SO_DELIVERY_FORM")]
        SO_DELIVERY_FORM,
        [EnumMember(Value = "SO_CONTRACT")]
        SO_CONTRACT,
        [EnumMember(Value = "PRODUCT_SHEET")]
        PRODUCT_SHEET,
        [EnumMember(Value = "WO_REPAIR_REPORT")]
        WO_REPAIR_REPORT,
    }
}
