// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets TenantAccessLevel</summary>
    public enum Body33_plus_TenantAccessLevelEnum {
        [EnumMember(Value = "AL_DISABLED")]
        AL_DISABLED,
        [EnumMember(Value = "AL_ADMIN")]
        AL_ADMIN,
        [EnumMember(Value = "AL_STANDARD")]
        AL_STANDARD,
        [EnumMember(Value = "AL_CUSTOMER_PORTAL")]
        AL_CUSTOMER_PORTAL,
        [EnumMember(Value = "AL_CUSTOM")]
        AL_CUSTOM,
    }
}
