// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets PricingType</summary>
    public enum Body14_plus_PricingTypeEnum {
        [EnumMember(Value = "FIXED_PRICE")]
        FIXED_PRICE,
        [EnumMember(Value = "HOURLY_RATE")]
        HOURLY_RATE,
    }
}
