// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class Body114 : IParsable {
        /// <summary>Gets or Sets DeliveryAttempt</summary>
        public double? DeliveryAttempt { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Skmxrmv1beta1eventHandlerswebhookRxOnePubSubV1Message? Message { get; set; }
#nullable restore
#else
        public Skmxrmv1beta1eventHandlerswebhookRxOnePubSubV1Message Message { get; set; }
#endif
        /// <summary>Gets or Sets Subscription</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subscription { get; set; }
#nullable restore
#else
        public string Subscription { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Body114 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Body114();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"deliveryAttempt", n => { DeliveryAttempt = n.GetDoubleValue(); } },
                {"message", n => { Message = n.GetObjectValue<Skmxrmv1beta1eventHandlerswebhookRxOnePubSubV1Message>(Skmxrmv1beta1eventHandlerswebhookRxOnePubSubV1Message.CreateFromDiscriminatorValue); } },
                {"subscription", n => { Subscription = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("deliveryAttempt", DeliveryAttempt);
            writer.WriteObjectValue<Skmxrmv1beta1eventHandlerswebhookRxOnePubSubV1Message>("message", Message);
            writer.WriteStringValue("subscription", Subscription);
        }
    }
}
