// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets SubscriptionPeriodType</summary>
    public enum Body59_plus_SubscriptionPeriodTypeEnum {
        [EnumMember(Value = "MONTH")]
        MONTH,
        [EnumMember(Value = "YEAR")]
        YEAR,
    }
}
