// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class Body46 : IParsable {
        /// <summary>Gets or Sets FollowupBy</summary>
        public DateTimeOffset? FollowupBy { get; set; }
        /// <summary>Gets or Sets HardwareId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HardwareId { get; set; }
#nullable restore
#else
        public string HardwareId { get; set; }
#endif
        /// <summary>The _hashes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse2004Hashes? Hashes { get; set; }
#nullable restore
#else
        public InlineResponse2004Hashes Hashes { get; set; }
#endif
        /// <summary>Gets or Sets InvoiceCustomerId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceCustomerId { get; set; }
#nullable restore
#else
        public string InvoiceCustomerId { get; set; }
#endif
        /// <summary>Gets or Sets IsArchived</summary>
        public bool? IsArchived { get; set; }
        /// <summary>Gets or Sets LineItems</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<InlineResponse20016OrderLines>? LineItems { get; set; }
#nullable restore
#else
        public List<InlineResponse20016OrderLines> LineItems { get; set; }
#endif
        /// <summary>The mainAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Xrmdbv1beta1tenantstenantIdemployeesMainAddress? MainAddress { get; set; }
#nullable restore
#else
        public Xrmdbv1beta1tenantstenantIdemployeesMainAddress MainAddress { get; set; }
#endif
        /// <summary>Gets or Sets No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? No { get; set; }
#nullable restore
#else
        public string No { get; set; }
#endif
        /// <summary>Gets or Sets OurContactId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OurContactId { get; set; }
#nullable restore
#else
        public string OurContactId { get; set; }
#endif
        /// <summary>Gets or Sets PrimaryContactId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryContactId { get; set; }
#nullable restore
#else
        public string PrimaryContactId { get; set; }
#endif
        /// <summary>Gets or Sets PriorityCode</summary>
        public Body46_plus_PriorityCodeEnum? PriorityCode { get; set; }
        /// <summary>Gets or Sets ProjectId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Gets or Sets ResolveBy</summary>
        public DateTimeOffset? ResolveBy { get; set; }
        /// <summary>Gets or Sets Status</summary>
        public Body46_plus_StatusEnum? Status { get; set; }
        /// <summary>Gets or Sets Title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Gets or Sets UnsafeHtmlCaseText</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnsafeHtmlCaseText { get; set; }
#nullable restore
#else
        public string UnsafeHtmlCaseText { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Body46 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Body46();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"followupBy", n => { FollowupBy = n.GetDateTimeOffsetValue(); } },
                {"hardwareId", n => { HardwareId = n.GetStringValue(); } },
                {"_hashes", n => { Hashes = n.GetObjectValue<InlineResponse2004Hashes>(InlineResponse2004Hashes.CreateFromDiscriminatorValue); } },
                {"invoiceCustomerId", n => { InvoiceCustomerId = n.GetStringValue(); } },
                {"isArchived", n => { IsArchived = n.GetBoolValue(); } },
                {"lineItems", n => { LineItems = n.GetCollectionOfObjectValues<InlineResponse20016OrderLines>(InlineResponse20016OrderLines.CreateFromDiscriminatorValue)?.ToList(); } },
                {"mainAddress", n => { MainAddress = n.GetObjectValue<Xrmdbv1beta1tenantstenantIdemployeesMainAddress>(Xrmdbv1beta1tenantstenantIdemployeesMainAddress.CreateFromDiscriminatorValue); } },
                {"no", n => { No = n.GetStringValue(); } },
                {"ourContactId", n => { OurContactId = n.GetStringValue(); } },
                {"primaryContactId", n => { PrimaryContactId = n.GetStringValue(); } },
                {"priorityCode", n => { PriorityCode = n.GetEnumValue<Body46_plus_PriorityCodeEnum>(); } },
                {"projectId", n => { ProjectId = n.GetStringValue(); } },
                {"resolveBy", n => { ResolveBy = n.GetDateTimeOffsetValue(); } },
                {"status", n => { Status = n.GetEnumValue<Body46_plus_StatusEnum>(); } },
                {"title", n => { Title = n.GetStringValue(); } },
                {"unsafeHtmlCaseText", n => { UnsafeHtmlCaseText = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("followupBy", FollowupBy);
            writer.WriteStringValue("hardwareId", HardwareId);
            writer.WriteObjectValue<InlineResponse2004Hashes>("_hashes", Hashes);
            writer.WriteStringValue("invoiceCustomerId", InvoiceCustomerId);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteCollectionOfObjectValues<InlineResponse20016OrderLines>("lineItems", LineItems);
            writer.WriteObjectValue<Xrmdbv1beta1tenantstenantIdemployeesMainAddress>("mainAddress", MainAddress);
            writer.WriteStringValue("no", No);
            writer.WriteStringValue("ourContactId", OurContactId);
            writer.WriteStringValue("primaryContactId", PrimaryContactId);
            writer.WriteEnumValue<Body46_plus_PriorityCodeEnum>("priorityCode", PriorityCode);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteDateTimeOffsetValue("resolveBy", ResolveBy);
            writer.WriteEnumValue<Body46_plus_StatusEnum>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("unsafeHtmlCaseText", UnsafeHtmlCaseText);
        }
    }
}
