// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class Body51 : IParsable {
        /// <summary>Gets or Sets Currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Gets or Sets CustomerContactId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerContactId { get; set; }
#nullable restore
#else
        public string CustomerContactId { get; set; }
#endif
        /// <summary>Gets or Sets EstimatedClosingAt</summary>
        public DateTimeOffset? EstimatedClosingAt { get; set; }
        /// <summary>Gets or Sets EstimatedProbabilityPct</summary>
        public double? EstimatedProbabilityPct { get; set; }
        /// <summary>Gets or Sets EstimatedWorth</summary>
        public double? EstimatedWorth { get; set; }
        /// <summary>The _hashes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse2004Hashes? Hashes { get; set; }
#nullable restore
#else
        public InlineResponse2004Hashes Hashes { get; set; }
#endif
        /// <summary>Gets or Sets IsArchived</summary>
        public bool? IsArchived { get; set; }
        /// <summary>Gets or Sets Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or Sets NextFollowUpAt</summary>
        public DateTimeOffset? NextFollowUpAt { get; set; }
        /// <summary>Gets or Sets No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? No { get; set; }
#nullable restore
#else
        public string No { get; set; }
#endif
        /// <summary>Gets or Sets OptyFase</summary>
        public Body51_plus_OptyFaseEnum? OptyFase { get; set; }
        /// <summary>Gets or Sets OurContactId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OurContactId { get; set; }
#nullable restore
#else
        public string OurContactId { get; set; }
#endif
        /// <summary>Gets or Sets ProjectId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Gets or Sets ProjectType</summary>
        public Body51_plus_ProjectTypeEnum? ProjectType { get; set; }
        /// <summary>Gets or Sets UnsafeHtmlDescription</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnsafeHtmlDescription { get; set; }
#nullable restore
#else
        public string UnsafeHtmlDescription { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Body51 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Body51();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"currency", n => { Currency = n.GetStringValue(); } },
                {"customerContactId", n => { CustomerContactId = n.GetStringValue(); } },
                {"estimatedClosingAt", n => { EstimatedClosingAt = n.GetDateTimeOffsetValue(); } },
                {"estimatedProbabilityPct", n => { EstimatedProbabilityPct = n.GetDoubleValue(); } },
                {"estimatedWorth", n => { EstimatedWorth = n.GetDoubleValue(); } },
                {"_hashes", n => { Hashes = n.GetObjectValue<InlineResponse2004Hashes>(InlineResponse2004Hashes.CreateFromDiscriminatorValue); } },
                {"isArchived", n => { IsArchived = n.GetBoolValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"nextFollowUpAt", n => { NextFollowUpAt = n.GetDateTimeOffsetValue(); } },
                {"no", n => { No = n.GetStringValue(); } },
                {"optyFase", n => { OptyFase = n.GetEnumValue<Body51_plus_OptyFaseEnum>(); } },
                {"ourContactId", n => { OurContactId = n.GetStringValue(); } },
                {"projectId", n => { ProjectId = n.GetStringValue(); } },
                {"projectType", n => { ProjectType = n.GetEnumValue<Body51_plus_ProjectTypeEnum>(); } },
                {"unsafeHtmlDescription", n => { UnsafeHtmlDescription = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("customerContactId", CustomerContactId);
            writer.WriteDateTimeOffsetValue("estimatedClosingAt", EstimatedClosingAt);
            writer.WriteDoubleValue("estimatedProbabilityPct", EstimatedProbabilityPct);
            writer.WriteDoubleValue("estimatedWorth", EstimatedWorth);
            writer.WriteObjectValue<InlineResponse2004Hashes>("_hashes", Hashes);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("nextFollowUpAt", NextFollowUpAt);
            writer.WriteStringValue("no", No);
            writer.WriteEnumValue<Body51_plus_OptyFaseEnum>("optyFase", OptyFase);
            writer.WriteStringValue("ourContactId", OurContactId);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteEnumValue<Body51_plus_ProjectTypeEnum>("projectType", ProjectType);
            writer.WriteStringValue("unsafeHtmlDescription", UnsafeHtmlDescription);
        }
    }
}
