// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets SellingUnit</summary>
    public enum Body13_plus_SellingUnitEnum {
        [EnumMember(Value = "STK")]
        STK,
        [EnumMember(Value = "KG")]
        KG,
        [EnumMember(Value = "METERS")]
        METERS,
        [EnumMember(Value = "HOURS")]
        HOURS,
        [EnumMember(Value = "M2")]
        M2,
        [EnumMember(Value = "LITRES")]
        LITRES,
        [EnumMember(Value = "M3")]
        M3,
    }
}
