// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse20064 : IParsable {
        /// <summary>Gets or Sets CreatedEntityId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedEntityId { get; set; }
#nullable restore
#else
        public string CreatedEntityId { get; set; }
#endif
        /// <summary>Gets or Sets CreatedEntityType</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedEntityType { get; set; }
#nullable restore
#else
        public string CreatedEntityType { get; set; }
#endif
        /// <summary>Gets or Sets UiViewUrl</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UiViewUrl { get; set; }
#nullable restore
#else
        public string UiViewUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse20064 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse20064();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"createdEntityId", n => { CreatedEntityId = n.GetStringValue(); } },
                {"createdEntityType", n => { CreatedEntityType = n.GetStringValue(); } },
                {"uiViewUrl", n => { UiViewUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdEntityId", CreatedEntityId);
            writer.WriteStringValue("createdEntityType", CreatedEntityType);
            writer.WriteStringValue("uiViewUrl", UiViewUrl);
        }
    }
}
