// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse2008MainAddressGeoPoint : IParsable {
        /// <summary>Gets or Sets Bbox</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Bbox { get; set; }
#nullable restore
#else
        public List<double?> Bbox { get; set; }
#endif
        /// <summary>Gets or Sets Coordinates</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Coordinates { get; set; }
#nullable restore
#else
        public List<double?> Coordinates { get; set; }
#endif
        /// <summary>Gets or Sets Type</summary>
        public InlineResponse2008MainAddressGeoPoint_plus_TypeEnum? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse2008MainAddressGeoPoint CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse2008MainAddressGeoPoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"bbox", n => { Bbox = n.GetCollectionOfPrimitiveValues<double?>()?.ToList(); } },
                {"coordinates", n => { Coordinates = n.GetCollectionOfPrimitiveValues<double?>()?.ToList(); } },
                {"type", n => { Type = n.GetEnumValue<InlineResponse2008MainAddressGeoPoint_plus_TypeEnum>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<double?>("bbox", Bbox);
            writer.WriteCollectionOfPrimitiveValues<double?>("coordinates", Coordinates);
            writer.WriteEnumValue<InlineResponse2008MainAddressGeoPoint_plus_TypeEnum>("type", Type);
        }
    }
}
