// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse200PrimaryTenantMetaMenusMetaItems : IParsable {
        /// <summary>Gets or Sets Children</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Children { get; set; }
#nullable restore
#else
        public List<string> Children { get; set; }
#endif
        /// <summary>Gets or Sets Cmd</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cmd { get; set; }
#nullable restore
#else
        public string Cmd { get; set; }
#endif
        /// <summary>Gets or Sets Icon</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>Gets or Sets Label</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Gets or Sets Props</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaMenusMetaItems_props? Props { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaMenusMetaItems_props Props { get; set; }
#endif
        /// <summary>Gets or Sets Tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Gets or Sets Type</summary>
        public InlineResponse200PrimaryTenantMetaMenusMetaItems_plus_TypeEnum? Type { get; set; }
        /// <summary>Gets or Sets Url</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse200PrimaryTenantMetaMenusMetaItems CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse200PrimaryTenantMetaMenusMetaItems();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"children", n => { Children = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"cmd", n => { Cmd = n.GetStringValue(); } },
                {"icon", n => { Icon = n.GetStringValue(); } },
                {"label", n => { Label = n.GetStringValue(); } },
                {"props", n => { Props = n.GetObjectValue<InlineResponse200PrimaryTenantMetaMenusMetaItems_props>(InlineResponse200PrimaryTenantMetaMenusMetaItems_props.CreateFromDiscriminatorValue); } },
                {"tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"type", n => { Type = n.GetEnumValue<InlineResponse200PrimaryTenantMetaMenusMetaItems_plus_TypeEnum>(); } },
                {"url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("children", Children);
            writer.WriteStringValue("cmd", Cmd);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaMenusMetaItems_props>("props", Props);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteEnumValue<InlineResponse200PrimaryTenantMetaMenusMetaItems_plus_TypeEnum>("type", Type);
            writer.WriteStringValue("url", Url);
        }
    }
}
