// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets Type</summary>
    public enum InlineResponse200PrimaryTenantMetaColors_plus_TypeEnum {
        [EnumMember(Value = "BRAND")]
        BRAND,
        [EnumMember(Value = "CHARTJS_SCHEME")]
        CHARTJS_SCHEME,
    }
}
