// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse20053 : IParsable {
        /// <summary>The emailProviderConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse20053EmailProviderConfig? EmailProviderConfig { get; set; }
#nullable restore
#else
        public InlineResponse20053EmailProviderConfig EmailProviderConfig { get; set; }
#endif
        /// <summary>The emailProviderInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse20053EmailProviderInfo? EmailProviderInfo { get; set; }
#nullable restore
#else
        public InlineResponse20053EmailProviderInfo EmailProviderInfo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse20053 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse20053();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"emailProviderConfig", n => { EmailProviderConfig = n.GetObjectValue<InlineResponse20053EmailProviderConfig>(InlineResponse20053EmailProviderConfig.CreateFromDiscriminatorValue); } },
                {"emailProviderInfo", n => { EmailProviderInfo = n.GetObjectValue<InlineResponse20053EmailProviderInfo>(InlineResponse20053EmailProviderInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<InlineResponse20053EmailProviderConfig>("emailProviderConfig", EmailProviderConfig);
            writer.WriteObjectValue<InlineResponse20053EmailProviderInfo>("emailProviderInfo", EmailProviderInfo);
        }
    }
}
