// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse20050 : IParsable {
        /// <summary>Gets or Sets Colors</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<InlineResponse200PrimaryTenantMetaColors>? Colors { get; set; }
#nullable restore
#else
        public List<InlineResponse200PrimaryTenantMetaColors> Colors { get; set; }
#endif
        /// <summary>Gets or Sets Currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Gets or Sets SystemName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemName { get; set; }
#nullable restore
#else
        public string SystemName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse20050 CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse20050();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"colors", n => { Colors = n.GetCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaColors>(InlineResponse200PrimaryTenantMetaColors.CreateFromDiscriminatorValue)?.ToList(); } },
                {"currency", n => { Currency = n.GetStringValue(); } },
                {"systemName", n => { SystemName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaColors>("colors", Colors);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("systemName", SystemName);
        }
    }
}
