// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse200PrimaryTenantMetaProperties : IParsable {
        /// <summary>Gets or Sets DataTypeId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataTypeId { get; set; }
#nullable restore
#else
        public string DataTypeId { get; set; }
#endif
        /// <summary>Gets or Sets DefaultValue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultValue { get; set; }
#nullable restore
#else
        public string DefaultValue { get; set; }
#endif
        /// <summary>Gets or Sets EnumOptions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<InlineResponse200PrimaryTenantMetaEnumOptions>? EnumOptions { get; set; }
#nullable restore
#else
        public List<InlineResponse200PrimaryTenantMetaEnumOptions> EnumOptions { get; set; }
#endif
        /// <summary>The foreignKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaForeignKey? ForeignKey { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaForeignKey ForeignKey { get; set; }
#endif
        /// <summary>Gets or Sets FormInputConfig</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaProperties_formInputConfig? FormInputConfig { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaProperties_formInputConfig FormInputConfig { get; set; }
#endif
        /// <summary>Gets or Sets FormInputType</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormInputType { get; set; }
#nullable restore
#else
        public string FormInputType { get; set; }
#endif
        /// <summary>Gets or Sets Freadonly</summary>
        public bool? Freadonly { get; set; }
        /// <summary>Gets or Sets Id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or Sets IsCopyIgnored</summary>
        public bool? IsCopyIgnored { get; set; }
        /// <summary>Gets or Sets IsImmutable</summary>
        public bool? IsImmutable { get; set; }
        /// <summary>Gets or Sets IsRequired</summary>
        public bool? IsRequired { get; set; }
        /// <summary>Gets or Sets IsUniqueIndex</summary>
        public bool? IsUniqueIndex { get; set; }
        /// <summary>Gets or Sets JsonBaseType</summary>
        public InlineResponse200PrimaryTenantMetaProperties_plus_JsonBaseTypeEnum? JsonBaseType { get; set; }
        /// <summary>Gets or Sets Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or Sets SubdocEntityType</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubdocEntityType { get; set; }
#nullable restore
#else
        public string SubdocEntityType { get; set; }
#endif
        /// <summary>Gets or Sets TableColumnConfig</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaProperties_tableColumnConfig? TableColumnConfig { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaProperties_tableColumnConfig TableColumnConfig { get; set; }
#endif
        /// <summary>Gets or Sets TableColumnFormatter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TableColumnFormatter { get; set; }
#nullable restore
#else
        public string TableColumnFormatter { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse200PrimaryTenantMetaProperties CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse200PrimaryTenantMetaProperties();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"dataTypeId", n => { DataTypeId = n.GetStringValue(); } },
                {"defaultValue", n => { DefaultValue = n.GetStringValue(); } },
                {"enumOptions", n => { EnumOptions = n.GetCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaEnumOptions>(InlineResponse200PrimaryTenantMetaEnumOptions.CreateFromDiscriminatorValue)?.ToList(); } },
                {"foreignKey", n => { ForeignKey = n.GetObjectValue<InlineResponse200PrimaryTenantMetaForeignKey>(InlineResponse200PrimaryTenantMetaForeignKey.CreateFromDiscriminatorValue); } },
                {"formInputConfig", n => { FormInputConfig = n.GetObjectValue<InlineResponse200PrimaryTenantMetaProperties_formInputConfig>(InlineResponse200PrimaryTenantMetaProperties_formInputConfig.CreateFromDiscriminatorValue); } },
                {"formInputType", n => { FormInputType = n.GetStringValue(); } },
                {"freadonly", n => { Freadonly = n.GetBoolValue(); } },
                {"id", n => { Id = n.GetStringValue(); } },
                {"isCopyIgnored", n => { IsCopyIgnored = n.GetBoolValue(); } },
                {"isImmutable", n => { IsImmutable = n.GetBoolValue(); } },
                {"isRequired", n => { IsRequired = n.GetBoolValue(); } },
                {"isUniqueIndex", n => { IsUniqueIndex = n.GetBoolValue(); } },
                {"jsonBaseType", n => { JsonBaseType = n.GetEnumValue<InlineResponse200PrimaryTenantMetaProperties_plus_JsonBaseTypeEnum>(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"subdocEntityType", n => { SubdocEntityType = n.GetStringValue(); } },
                {"tableColumnConfig", n => { TableColumnConfig = n.GetObjectValue<InlineResponse200PrimaryTenantMetaProperties_tableColumnConfig>(InlineResponse200PrimaryTenantMetaProperties_tableColumnConfig.CreateFromDiscriminatorValue); } },
                {"tableColumnFormatter", n => { TableColumnFormatter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dataTypeId", DataTypeId);
            writer.WriteStringValue("defaultValue", DefaultValue);
            writer.WriteCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaEnumOptions>("enumOptions", EnumOptions);
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaForeignKey>("foreignKey", ForeignKey);
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaProperties_formInputConfig>("formInputConfig", FormInputConfig);
            writer.WriteStringValue("formInputType", FormInputType);
            writer.WriteBoolValue("freadonly", Freadonly);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isCopyIgnored", IsCopyIgnored);
            writer.WriteBoolValue("isImmutable", IsImmutable);
            writer.WriteBoolValue("isRequired", IsRequired);
            writer.WriteBoolValue("isUniqueIndex", IsUniqueIndex);
            writer.WriteEnumValue<InlineResponse200PrimaryTenantMetaProperties_plus_JsonBaseTypeEnum>("jsonBaseType", JsonBaseType);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("subdocEntityType", SubdocEntityType);
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaProperties_tableColumnConfig>("tableColumnConfig", TableColumnConfig);
            writer.WriteStringValue("tableColumnFormatter", TableColumnFormatter);
        }
    }
}
