// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets AggFormat</summary>
    public enum InlineResponse2002AggsString_plus_AggFormatEnum {
        [EnumMember(Value = "basic1")]
        Basic1,
        [EnumMember(Value = "chartjs1")]
        Chartjs1,
        [EnumMember(Value = "chartjs3")]
        Chartjs3,
        [EnumMember(Value = "todo9")]
        Todo9,
    }
}
