// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse200PrimaryTenantMetaColors : IParsable {
        /// <summary>The brandColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaBrandColor? BrandColor { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaBrandColor BrandColor { get; set; }
#endif
        /// <summary>The chartjsScheme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public InlineResponse200PrimaryTenantMetaChartjsScheme? ChartjsScheme { get; set; }
#nullable restore
#else
        public InlineResponse200PrimaryTenantMetaChartjsScheme ChartjsScheme { get; set; }
#endif
        /// <summary>Gets or Sets Type</summary>
        public InlineResponse200PrimaryTenantMetaColors_plus_TypeEnum? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse200PrimaryTenantMetaColors CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse200PrimaryTenantMetaColors();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"brandColor", n => { BrandColor = n.GetObjectValue<InlineResponse200PrimaryTenantMetaBrandColor>(InlineResponse200PrimaryTenantMetaBrandColor.CreateFromDiscriminatorValue); } },
                {"chartjsScheme", n => { ChartjsScheme = n.GetObjectValue<InlineResponse200PrimaryTenantMetaChartjsScheme>(InlineResponse200PrimaryTenantMetaChartjsScheme.CreateFromDiscriminatorValue); } },
                {"type", n => { Type = n.GetEnumValue<InlineResponse200PrimaryTenantMetaColors_plus_TypeEnum>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaBrandColor>("brandColor", BrandColor);
            writer.WriteObjectValue<InlineResponse200PrimaryTenantMetaChartjsScheme>("chartjsScheme", ChartjsScheme);
            writer.WriteEnumValue<InlineResponse200PrimaryTenantMetaColors_plus_TypeEnum>("type", Type);
        }
    }
}
