// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.Core.Pointer.Models {
    public class InlineResponse200PrimaryTenantMetaMenusMetaMenus : IParsable {
        /// <summary>Gets or Sets Items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<InlineResponse200PrimaryTenantMetaMenusMetaItems>? Items { get; set; }
#nullable restore
#else
        public List<InlineResponse200PrimaryTenantMetaMenusMetaItems> Items { get; set; }
#endif
        /// <summary>Gets or Sets MenuId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuId { get; set; }
#nullable restore
#else
        public string MenuId { get; set; }
#endif
        /// <summary>Gets or Sets ShowLabels</summary>
        public bool? ShowLabels { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static InlineResponse200PrimaryTenantMetaMenusMetaMenus CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new InlineResponse200PrimaryTenantMetaMenusMetaMenus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"items", n => { Items = n.GetCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaMenusMetaItems>(InlineResponse200PrimaryTenantMetaMenusMetaItems.CreateFromDiscriminatorValue)?.ToList(); } },
                {"menuId", n => { MenuId = n.GetStringValue(); } },
                {"showLabels", n => { ShowLabels = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<InlineResponse200PrimaryTenantMetaMenusMetaItems>("items", Items);
            writer.WriteStringValue("menuId", MenuId);
            writer.WriteBoolValue("showLabels", ShowLabels);
        }
    }
}
