// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets ConflictBehavior</summary>
    public enum Xrmdbv1beta1tenantstenantIddriveItemscreateUploadFiles_plus_ConflictBehaviorEnum {
        [EnumMember(Value = "FAIL")]
        FAIL,
        [EnumMember(Value = "REPLACE")]
        REPLACE,
        [EnumMember(Value = "RENAME")]
        RENAME,
    }
}
