// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Qwips.Core.Pointer.Models {
    /// <summary>Gets or Sets Format</summary>
    public enum Xrmpdfgenv1beta1tenantstenantIdgotenberghtml1TemplateParts_plus_FormatEnum {
        [EnumMember(Value = "NONE")]
        NONE,
        [EnumMember(Value = "HANDLEBARS_HTML_T1")]
        HANDLEBARS_HTML_T1,
        [EnumMember(Value = "HANDLEBARS_HTML_PDFGEN_T1")]
        HANDLEBARS_HTML_PDFGEN_T1,
        [EnumMember(Value = "SASS_STRICT_T1")]
        SASS_STRICT_T1,
        [EnumMember(Value = "SASS_PDFGEN_T1")]
        SASS_PDFGEN_T1,
    }
}
